# Generated by Django 4.2.1 on 2023-05-05 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('project_description', models.TextField()),
                ('project_technology', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('is_home', models.BooleanField(default=False)),
            ],
        ),
    ]
