# Generated by Django 4.2.1 on 2023-05-05 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_projectmodels_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodels',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
