# Generated by Django 4.2.1 on 2023-05-06 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_projectmodels_project_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmodels',
            name='project_owner',
        ),
    ]
