# Generated by Django 4.2.1 on 2023-05-06 16:32

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_projectmodels_project_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodels',
            name='project_owner',
            field=models.CharField(default=None, max_length=100, verbose_name=django.contrib.auth.models.User),
        ),
    ]
