# Generated by Django 4.2.1 on 2023-05-16 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_projectmodels_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodels',
            name='project_description',
            field=models.TextField(max_length=250),
        ),
    ]
