# Generated by Django 4.2.1 on 2023-05-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_alter_projectmodels_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodels',
            name='add',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectmodels',
            name='dont_add',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='projectmodels',
            name='project_name',
            field=models.CharField(max_length=20),
        ),
    ]
