# Generated by Django 4.2.1 on 2023-05-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_alter_projectmodels_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodels',
            name='authorized',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
